apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

commonLabels:
  app.kubernetes.io/part-of: fintext-alpha-vectorizer
  environment: production
  tier: database-backups

resources:
  - postgres-backup-cronjob.yaml
  - questdb-backup-cronjob.yaml
  - restore-test-cronjob.yaml
