apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

commonLabels:
  app.kubernetes.io/part-of: fintext-alpha-vectorizer
  environment: production
  tier: progressive-delivery

resources:
  - flagger-canary-api.yaml
  - flagger-canary-ingestion.yaml
  - flagger-canary-spillover.yaml
  - flyway-migration-job.yaml
  - atlas-migration-job.yaml
