//! ═══════════════════════════════════════════════════════════════════════════════
//! FinText-Alpha-Vectorizer — OpenAPI 3.0 Documentation & Swagger UI Spec
//! ═══════════════════════════════════════════════════════════════════════════════

use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
use utoipa::{Modify, OpenApi};

use crate::audit_logs::{
    AuditExportQuery, AuditLogEntry, AuditLogExportResponse, AuditLogsQuery, AuditLogsResponse,
};
use crate::auth::{AuthErrorResponse, IssueTokenRequest, IssueTokenResponse};
use crate::billing::{
    BillingWebhookResponse, CheckoutRequest, CheckoutResponse, PortalRequest, PortalResponse,
    SubscriptionResponse,
};
use crate::handlers::audio_transcribe::AudioTranscribeParams;
use crate::handlers::export::ExportCsvParams;
use crate::ip_whitelist::{
    AddIpWhitelistRequest, DeleteIpWhitelistResponse, IpWhitelistEntry, IpWhitelistErrorResponse,
    ListIpWhitelistResponse,
};
use crate::models::{
    AbnormalReturnPoint, AcousticFeatures, AlphaReportRequest, AlphaReportResponse,
    AlphaSignalConfig, AnomalyScanResponse, AudioSentiment, AudioTranscriptionResponse,
    BackfillSentimentRequest, BackfillSentimentResponse, BacktestRequest, BacktestResponse,
    BankruptcyComponents, BankruptcyRiskResponse, BatchSentimentParams, BatchSentimentResponse,
    CalibrationPoint, ChatAlertSubscription, ChatAlertSubscriptionResponse, ChatAlertsResponse,
    ClassConfusion, ClassificationMetrics, CommoditySentimentArticle, CommoditySentimentResponse,
    CommoditySentimentSummary, ConfusionMatrix, CreateChatAlertRequest, CreateDigestRequest,
    CreateRetentionPolicyRequest, CreateRetrainingJobRequest, CreateTranscriptRequest,
    CreditSentimentResponse, CryptoSentimentArticle, CryptoSentimentResponse,
    CryptoSentimentSummary, DLQEventDetail, DLQEventItem, DLQEventsListResponse,
    DataProvenanceItem, DataProvenanceResponse, DecayCurvePoint, DeleteChatAlertResponse,
    DeleteDigestResponse, DeleteRetentionPolicyResponse, DeleteTranscriptResponse,
    DigestItemCounts, DigestSubscription, DigestSubscriptionResponse, ESGDimensionScore,
    ESGDimensions, ESGScoresResponse, EarningsSurpriseItem, EarningsSurpriseResponse, EightKFiling,
    EightKResponse, EntitySentimentItem, EntitySentimentResponse, EquityCurvePoint, EquityPoint,
    EventStudyResponse, ExportParquetParams, FIXCancelRequest, FIXOrderRequest, FIXOrderResponse,
    FIXOrdersListResponse, FXSentimentArticle, FXSentimentResponse, FXSentimentSummary,
    FactorExposureItem, FactorExposureResponse, FixOrderItem, HardwareRequirements, HealthResponse,
    ICSummary, InsiderTradeItem, InsiderTradingResponse, KafkaCredentials, KafkaTopicInfo,
    KafkaTopicsResponse, LanguageDetectionResponse, LicensingInfo, ListRetrainingJobsResponse,
    MARumorItem, MARumorsResponse, MarketBreadthPoint, MarketBreadthResponse, MarketCapBias,
    MarketRegimeResponse, MicrostructurePoint, MicrostructureResponse, ModelCardResponse,
    ModelMetadata, ModelValidationQuery, ModelValidationResponse, NewsArticleFull,
    NewsArticleMetadata, NewsArticlesListResponse, OLSStatistics, OptionContract, OptionsIvParams,
    OptionsIvResponse, OptionsVolSurfaceResponse, PITBackfillTestResult, PITCertificateParams,
    PITCertificatePolicies, PITCertificateResponse, PITCertificateTests, PITDuplicateTestResult,
    PITReplayConsistency, PITReplayEventItem, PITReplayFilingItem, PITReplayNewsItem,
    PITReplayResponse, PITReplaySentimentItem, PITReplaySummary, PITTestResult, PerClassMetrics,
    PerformanceMetrics, PortfolioConstraints, PortfolioFactorExposureRequest,
    PortfolioFactorExposureResponse, PortfolioOptimizeRequest, PortfolioOptimizeResponse,
    PortfolioWeight, ProcessingStep, ProviderHealthItem, ProviderHealthQuery,
    ProviderHealthResponse, PurgeDLQResponse, PutCallRatioPoint, PutCallRatioResponse,
    RegimeComponents, RegulatoryFilingItem, RegulatoryFilingsResponse, ReprocessDLQResponse,
    RetentionPoliciesResponse, RetentionPolicy, RetrainingJob, RetrainingJobResponse,
    ReturnCorrelationItem, ReturnCorrelationResponse, RevokeKafkaCredentialsResponse,
    SLALatencyResponse, SLAStatusResponse, SandboxStatusResponse, SearchParams, SearchResponse,
    SearchResultItem, SectorRotationItem, SectorRotationResponse, SectorSentimentParams,
    SectorSentimentResponse, SentimentAnomaliesParams, SentimentAnomaliesResponse,
    SentimentAnomalyAlert, SentimentAnomalyItem, SentimentDisagreementResponse,
    SentimentEntitiesParams, SentimentFeedItem, SentimentFeedParams, SentimentFeedResponse,
    SentimentHistoryParams, SentimentHistoryResponse, SentimentProbabilities, SentimentRecord,
    SentimentResponse, SignalQualityReportRequest, SignalQualityReportResponse, SourceBreakdown,
    SpilloverItem, SpilloverMatrixItem, SpilloverMatrixParams, SpilloverMatrixResponse,
    SpilloverResponse, StageBreakdown, SupplyChainRiskItem, SupplyChainRiskParams,
    SupplyChainRiskResponse, SymbolMapParams, SymbolMapResponse, TranscriptListParams,
    TranscriptListResponse, TranscriptMetadata, TranscriptResponse, TriggerDigestRequest,
    TriggerDigestResponse, UnusualOptionItem, UnusualOptionsParams, UnusualOptionsResponse,
    UsageGroupItem, UsageStatsParams, UsageStatsResponse, UsageStatsSummary, VersionHistoryItem,
    VolSurfacePoint,
};
use crate::orgs::{
    CreateOrgRequest, CreateOrgResponse, InviteMemberRequest, InviteMemberResponse,
    LeaveOrgResponse, ListOrgsResponse, OrgDetailsResponse, Organization, OrganizationMember,
    RemoveMemberResponse, SelectOrgResponse, UpdateMemberRoleRequest, UpdateMemberRoleResponse,
};
use crate::polling_webhooks::{
    CreatePollingWebhookRequest, DeletePollingWebhookResponse, PollingWebhookResponse,
    PollingWebhooksResponse,
};
use crate::rate_limit::RateLimitErrorResponse;
use crate::symbol_map::SecurityIdentifiers;
use crate::universes::{
    CreateUniverseRequest, DeleteUniverseResponse, ListUniversesParams, ListUniversesResponse,
    Universe, UpdateUniverseRequest,
};
use crate::users::{
    ApiKeyItem, CreateApiKeyRequest, CreateApiKeyResponse, DeleteApiKeyResponse,
    ListApiKeysResponse, LoginRequest, LoginResponse, RegisterRequest, RegisterResponse,
    RotateApiKeyRequest, RotateApiKeyResponse, UserProfileResponse,
};
use crate::webhooks::{
    CreateWebhookRequest, DeleteWebhookResponse, ListWebhooksResponse, WebhookPayload,
    WebhookResponse,
};

/// Security scheme modifier configuring Bearer JWT authentication for OpenAPI 3.0.
pub struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearerAuth",
                SecurityScheme::Http(
                    HttpBuilder::new()
                        .scheme(HttpAuthScheme::Bearer)
                        .bearer_format("JWT")
                        .description(Some(
                            "Enter your institutional JWT token obtained from `POST /auth/login` or `POST /auth/token` without the 'Bearer ' prefix.",
                        ))
                        .build(),
                ),
            );
        }
    }
}

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::handlers::health::health_check_handler,
        crate::auth::issue_token_handler,
        crate::users::register_user_handler,
        crate::users::login_user_handler,
        crate::users::get_me_handler,
        crate::users::create_api_key_handler,
        crate::users::list_api_keys_handler,
        crate::users::get_api_key_handler,
        crate::users::rotate_api_key_handler,
        crate::users::delete_api_key_handler,
        crate::handlers::transcripts::create_transcript_handler,
        crate::handlers::transcripts::list_transcripts_handler,
        crate::handlers::transcripts::get_transcript_handler,
        crate::handlers::transcripts::delete_transcript_handler,
        crate::handlers::audio_transcribe::transcribe_audio_handler,
        crate::handlers::market_regime::get_market_regime_handler,
        crate::handlers::return_correlation::get_return_correlation_handler,
        crate::handlers::sector_rotation::get_sector_rotation_handler,
        crate::handlers::market_breadth::get_market_breadth_handler,
        crate::handlers::put_call_ratio::get_put_call_ratio_handler,
        crate::handlers::sentiment::get_sentiment_handler,
        crate::handlers::sentiment_anomalies::get_sentiment_anomalies_handler,
        crate::handlers::sentiment_disagreement::get_sentiment_disagreement_handler,
        crate::handlers::sentiment_entities::get_sentiment_entities_handler,
        crate::handlers::sentiment_feed::get_sentiment_feed_handler,
        crate::handlers::sentiment_history::get_sentiment_history_handler,
        crate::handlers::sector_sentiment::get_sector_sentiment_handler,
        crate::handlers::batch_sentiment::get_batch_sentiment_handler,
        crate::handlers::scd2_revision::post_sentiment_revision_handler,
        crate::handlers::scd2_revision::get_sentiment_revisions_handler,
        crate::handlers::symbol_map::get_symbol_map_handler,
        crate::universes::create_universe_handler,
        crate::universes::list_universes_handler,
        crate::universes::get_universe_handler,
        crate::universes::update_universe_handler,
        crate::universes::delete_universe_handler,
        crate::handlers::spillovers::get_spillovers_handler,
        crate::handlers::spillover_matrix::get_spillover_matrix_handler,
        crate::handlers::options_iv::get_options_iv_handler,
        crate::handlers::options_unusual::get_unusual_options_handler,
        crate::handlers::options_vol_surface::get_options_vol_surface_handler,
        crate::handlers::options_microstructure::get_options_microstructure_handler,
        crate::handlers::usage_stats::get_usage_stats_handler,
        crate::handlers::event_study::get_event_study_handler,
        crate::handlers::events_8k::get_8k_events_handler,
        crate::handlers::earnings_surprise::get_earnings_surprise_handler,
        crate::handlers::insider_trading::get_insider_trading_handler,
        crate::handlers::ma_rumors::get_ma_rumors_handler,
        crate::handlers::regulatory_filings::get_regulatory_filings_handler,
        crate::handlers::supply_chain_risk::get_supply_chain_risk_handler,
        crate::handlers::backtest::backtest_handler,
        crate::handlers::export::export_csv_handler,
        crate::handlers::export_parquet::export_parquet_handler,
        crate::webhooks::register_webhook_handler,
        crate::webhooks::list_webhooks_handler,
        crate::webhooks::delete_webhook_handler,
        crate::billing::create_checkout_handler,
        crate::billing::create_portal_handler,
        crate::billing::get_subscription_handler,
        crate::billing::stripe_webhook_handler,
        crate::orgs::create_org_handler,
        crate::orgs::list_orgs_handler,
        crate::orgs::get_org_handler,
        crate::orgs::invite_member_handler,
        crate::orgs::update_member_role_handler,
        crate::orgs::remove_member_handler,
        crate::orgs::leave_org_handler,
        crate::orgs::select_org_handler,
        crate::ip_whitelist::get_ip_whitelist_handler,
        crate::ip_whitelist::add_ip_whitelist_handler,
        crate::ip_whitelist::delete_ip_whitelist_handler,
        crate::handlers::news_articles::list_news_articles_handler,
        crate::handlers::news_articles::get_news_article_handler,
        crate::handlers::audit_logs::get_audit_logs_handler,
        crate::handlers::audit_logs::export_audit_logs_handler,
        crate::handlers::search::get_search_handler,
        crate::handlers::sector_rotation::get_sector_rotation_handler,
        crate::handlers::digest::get_digest_subscription_handler,
        crate::handlers::digest::create_digest_subscription_handler,
        crate::handlers::digest::delete_digest_subscription_handler,
        crate::handlers::digest::trigger_digest_send_handler,
        crate::handlers::kafka_stream::list_kafka_topics_handler,
        crate::handlers::kafka_stream::get_kafka_credentials_handler,
        crate::handlers::kafka_stream::revoke_kafka_credentials_handler,
        crate::handlers::retention::list_retention_policies_handler,
        crate::handlers::retention::create_retention_policy_handler,
        crate::handlers::retention::delete_retention_policy_handler,
        crate::handlers::factor_exposure::get_factor_exposure_handler,
        crate::handlers::esg_scores::get_esg_scores_handler,
        crate::handlers::bankruptcy_risk::get_bankruptcy_risk_handler,
        crate::handlers::fx_sentiment::get_fx_sentiment_handler,
        crate::handlers::commodity_sentiment::get_commodity_sentiment_handler,
        crate::handlers::crypto_sentiment::get_crypto_sentiment_handler,
        crate::polling_webhooks::create_polling_webhook_handler,
        crate::polling_webhooks::list_polling_webhooks_handler,
        crate::polling_webhooks::delete_polling_webhook_handler,
        crate::chat_alerts::create_chat_alert_handler,
        crate::chat_alerts::list_chat_alerts_handler,
        crate::chat_alerts::delete_chat_alert_handler,
        crate::handlers::credit_sentiment::get_credit_sentiment_handler,
        crate::handlers::backfill_sentiment::backfill_sentiment_handler,
        crate::handlers::portfolio_optimize::portfolio_optimize_handler,
        crate::handlers::portfolio_factor_exposure::portfolio_factor_exposure_handler,
        crate::handlers::retraining::create_retraining_job_handler,
        crate::handlers::retraining::list_retraining_jobs_handler,
        crate::handlers::retraining::get_retraining_job_handler,
        crate::handlers::retraining::cancel_retraining_job_handler,
        crate::handlers::fix_orders::submit_fix_order_handler,
        crate::handlers::fix_orders::list_fix_orders_handler,
        crate::handlers::fix_orders::cancel_fix_order_handler,
        crate::handlers::dlq::list_dlq_events_handler,
        crate::handlers::dlq::get_dlq_event_handler,
        crate::handlers::dlq::reprocess_dlq_event_handler,
        crate::handlers::dlq::purge_dlq_event_handler,
        crate::handlers::sla_status::get_sla_status_handler,
        crate::handlers::sla_latency::sla_latency_handler,
        crate::handlers::sandbox::activate_sandbox_handler,
        crate::handlers::sandbox::deactivate_sandbox_handler,
        crate::handlers::sandbox::get_sandbox_status_handler,
        crate::handlers::provenance::get_provenance_handler,
        crate::handlers::anomaly_scan::post_anomaly_scan_handler,
        crate::handlers::language_detect::get_language_detect_handler,
        crate::handlers::model_card::get_model_card_handler,
        crate::handlers::alpha_report::post_alpha_report_handler,
        crate::handlers::pit_replay::get_pit_replay_handler,
        crate::handlers::pit_certificate::get_pit_certificate_handler,
        crate::handlers::provider_health::get_provider_health_handler,
        crate::handlers::model_validation::get_model_validation_handler,
        crate::handlers::signal_quality::post_signal_quality_report_handler,
        crate::handlers::admin_pit::reload_pit_data_handler,
    ),
    components(
        schemas(
            crate::handlers::admin_pit::ReloadPitDataRequest,
            crate::handlers::admin_pit::ReloadPitDataResponse,
            HealthResponse,
            IssueTokenRequest,
            IssueTokenResponse,
            AuthErrorResponse,
            RegisterRequest,
            RegisterResponse,
            LoginRequest,
            LoginResponse,
            UserProfileResponse,
            CreateApiKeyRequest,
            CreateApiKeyResponse,
            RotateApiKeyRequest,
            RotateApiKeyResponse,
            ApiKeyItem,
            ListApiKeysResponse,
            DeleteApiKeyResponse,
            AcousticFeatures,
            AudioSentiment,
            AudioTranscriptionResponse,
            AudioTranscribeParams,
            CreateTranscriptRequest,
            TranscriptListParams,
            TranscriptMetadata,
            TranscriptResponse,
            TranscriptListResponse,
            DeleteTranscriptResponse,
            MarketRegimeResponse,
            RegimeComponents,
            ReturnCorrelationItem,
            ReturnCorrelationResponse,
            PutCallRatioPoint,
            PutCallRatioResponse,
            ModelMetadata,
            SentimentResponse,
            SentimentProbabilities,
            SentimentAnomaliesParams,
            SentimentAnomalyItem,
            SentimentAnomaliesResponse,
            SentimentDisagreementResponse,
            SentimentEntitiesParams,
            EntitySentimentItem,
            EntitySentimentResponse,
            SourceBreakdown,
            SentimentFeedParams,
            SentimentFeedItem,
            SentimentFeedResponse,
            SentimentHistoryParams,
            SentimentHistoryResponse,
            SentimentRecord,
            SectorSentimentParams,
            SectorSentimentResponse,
            BatchSentimentParams,
            BatchSentimentResponse,
            crate::scd2::RevisionIngestRequest,
            crate::scd2::RevisionIngestResponse,
            crate::scd2::RevisionHistoryListResponse,
            SecurityIdentifiers,
            SymbolMapParams,
            SymbolMapResponse,
            Universe,
            CreateUniverseRequest,
            UpdateUniverseRequest,
            ListUniversesParams,
            ListUniversesResponse,
            DeleteUniverseResponse,
            SpilloverItem,
            SpilloverResponse,
            SpilloverMatrixParams,
            SpilloverMatrixItem,
            SpilloverMatrixResponse,
            OptionContract,
            OptionsIvParams,
            OptionsIvResponse,
            OptionsVolSurfaceResponse,
            VolSurfacePoint,
            MicrostructurePoint,
            MicrostructureResponse,
            MarketBreadthPoint,
            MarketBreadthResponse,
            UnusualOptionItem,
            UnusualOptionsParams,
            UnusualOptionsResponse,
            UsageStatsParams,
            UsageStatsSummary,
            UsageGroupItem,
            UsageStatsResponse,
            AbnormalReturnPoint,
            EventStudyResponse,
            EightKFiling,
            EightKResponse,
            EarningsSurpriseItem,
            EarningsSurpriseResponse,
            InsiderTradeItem,
            InsiderTradingResponse,
            MARumorItem,
            MARumorsResponse,
            RegulatoryFilingItem,
            RegulatoryFilingsResponse,
            SupplyChainRiskItem,
            SupplyChainRiskParams,
            SupplyChainRiskResponse,
            BacktestRequest,
            BacktestResponse,
            EquityPoint,
            ExportCsvParams,
            ExportParquetParams,
            RateLimitErrorResponse,
            CreateWebhookRequest,
            WebhookResponse,
            ListWebhooksResponse,
            DeleteWebhookResponse,
            WebhookPayload,
            CheckoutRequest,
            CheckoutResponse,
            PortalRequest,
            PortalResponse,
            SubscriptionResponse,
            BillingWebhookResponse,
            Organization,
            OrganizationMember,
            CreateOrgRequest,
            CreateOrgResponse,
            ListOrgsResponse,
            OrgDetailsResponse,
            InviteMemberRequest,
            InviteMemberResponse,
            UpdateMemberRoleRequest,
            UpdateMemberRoleResponse,
            RemoveMemberResponse,
            LeaveOrgResponse,
            SelectOrgResponse,
            IpWhitelistEntry,
            AddIpWhitelistRequest,
            ListIpWhitelistResponse,
            DeleteIpWhitelistResponse,
            IpWhitelistErrorResponse,
            NewsArticleMetadata,
            NewsArticleFull,
            NewsArticlesListResponse,
            AuditLogEntry,
            AuditLogsQuery,
            AuditExportQuery,
            AuditLogsResponse,
            AuditLogExportResponse,
            SearchParams,
            SearchResultItem,
            SearchResponse,
            SectorRotationItem,
            SectorRotationResponse,
            DigestSubscription,
            CreateDigestRequest,
            DigestSubscriptionResponse,
            DeleteDigestResponse,
            TriggerDigestRequest,
            TriggerDigestResponse,
            DigestItemCounts,
            KafkaTopicInfo,
            KafkaTopicsResponse,
            KafkaCredentials,
            RevokeKafkaCredentialsResponse,
            RetentionPolicy,
            CreateRetentionPolicyRequest,
            RetentionPoliciesResponse,
            DeleteRetentionPolicyResponse,
            FactorExposureItem,
            OLSStatistics,
            FactorExposureResponse,
            ESGDimensionScore,
            ESGDimensions,
            ESGScoresResponse,
            BankruptcyComponents,
            BankruptcyRiskResponse,
            FXSentimentArticle,
            FXSentimentSummary,
            FXSentimentResponse,
            CommoditySentimentArticle,
            CommoditySentimentSummary,
            CommoditySentimentResponse,
            CryptoSentimentArticle,
            CryptoSentimentSummary,
            CryptoSentimentResponse,
            CreatePollingWebhookRequest,
            PollingWebhookResponse,
            PollingWebhooksResponse,
            DeletePollingWebhookResponse,
            ChatAlertSubscription,
            CreateChatAlertRequest,
            ChatAlertSubscriptionResponse,
            ChatAlertsResponse,
            DeleteChatAlertResponse,
            CreditSentimentResponse,
            BackfillSentimentRequest,
            BackfillSentimentResponse,
            PortfolioConstraints,
            PortfolioOptimizeRequest,
            PortfolioOptimizeResponse,
            PortfolioWeight,
            PortfolioFactorExposureRequest,
            PortfolioFactorExposureResponse,
            RetrainingJob,
            CreateRetrainingJobRequest,
            RetrainingJobResponse,
            ListRetrainingJobsResponse,
            FIXOrderRequest,
            FIXOrderResponse,
            FixOrderItem,
            FIXOrdersListResponse,
            FIXCancelRequest,
            DLQEventItem,
            DLQEventDetail,
            DLQEventsListResponse,
            ReprocessDLQResponse,
            PurgeDLQResponse,
            SLAStatusResponse,
            SLALatencyResponse,
            StageBreakdown,
            SandboxStatusResponse,
            ProcessingStep,
            DataProvenanceItem,
            DataProvenanceResponse,
            SentimentAnomalyAlert,
            AnomalyScanResponse,
            LanguageDetectionResponse,
            ModelCardResponse,
            HardwareRequirements,
            VersionHistoryItem,
            LicensingInfo,
            AlphaSignalConfig,
            AlphaReportRequest,
            PerformanceMetrics,
            EquityCurvePoint,
            AlphaReportResponse,
            PITReplayResponse,
            PITReplayNewsItem,
            PITReplayFilingItem,
            PITReplayEventItem,
            PITReplaySentimentItem,
            PITReplaySummary,
            PITReplayConsistency,
            PITCertificateResponse,
            PITCertificateTests,
            PITCertificatePolicies,
            PITTestResult,
            PITDuplicateTestResult,
            PITBackfillTestResult,
            SignalQualityReportRequest,
            SignalQualityReportResponse,
            ICSummary,
            DecayCurvePoint,
            MarketCapBias,
            ProviderHealthItem,
            ProviderHealthResponse,
            ProviderHealthQuery,
            CalibrationPoint,
            ClassConfusion,
            ClassificationMetrics,
            ConfusionMatrix,
            ModelValidationQuery,
            ModelValidationResponse,
            PerClassMetrics,
        )
    ),
    modifiers(&SecurityAddon),
    tags(
        (name = "System", description = "Liveness and system health monitoring probes"),
        (name = "Authentication", description = "User registration, login, JWT Token generation, and API key management"),
        (name = "Sandbox & Testing", description = "API Sandbox simulation environment, mock data isolation, and trial account testing"),
        (name = "Data Lineage & Governance", description = "Record-level data provenance tracing, model and pipeline version lineage, and processing audit histories"),
        (name = "Model Governance", description = "Standardized model card metadata, architecture specifications, training corpus lineage, and hardware requirements"),
        (name = "Trading & Execution", description = "FIX 4.4 protocol mock execution bridge, simulated order lifecycle, and order management"),
        (name = "Reliability & Operations", description = "Dead letter queue monitoring, failure inspection, event reprocessing, and quarantine management"),
        (name = "Sentiment Analysis", description = "Real-time and historical asset sentiment signals powered by QuestDB"),
        (name = "Model Retraining", description = "Autonomous ML model retraining pipeline, job scheduling, and version governance"),
        (name = "Custom Universes", description = "User-defined persistent asset universes and custom watchlists"),
        (name = "Cross-Asset Spillovers", description = "Lead-lag information transmission and Granger causality graph analytics"),
        (name = "Options & Derivatives", description = "Analytical Black-Scholes implied volatility (IV) and option Greeks (Delta, Gamma, Theta, Vega, Rho)"),
        (name = "Usage & Analytics", description = "Historical API consumption analytics, endpoint breakdowns, and latency metrics"),
        (name = "Usage & SLA", description = "API consumption analytics, latency percentiles, and contractual SLA compliance monitoring"),
        (name = "Quantitative Backtesting", description = "Point-in-time historical simulation, metrics, and equity curve generation"),
        (name = "Historical Data Export", description = "Streamed CSV historical datasets for quant research and offline backtesting"),
        (name = "Webhooks", description = "Asynchronous HTTP push notification subscriptions and event dispatching"),
        (name = "WebSocket Streaming", description = "Real-time pub/sub sentiment stream at `ws://<host>:<port>/ws?token=<JWT>`"),
        (name = "Billing & Subscriptions", description = "Stripe-powered subscription billing, checkout, customer portal, and plan management"),
        (name = "Organizations & Teams", description = "Multi-tenant organization management, team hierarchy, RBAC, and context switching"),
        (name = "Security & IP Whitelisting", description = "Per-user and organization IP and CIDR range access control"),
        (name = "Financial News & Full Text", description = "Institutional financial news feed, query filtering, and full article text retrieval"),
        (name = "Compliance & Audit", description = "Regulatory-grade audit trail, event logging, and CSV/JSON export"),
        (name = "Search", description = "Unified full-text and cross-domain search across news, transcripts, filings, sentiment, events, insider trades, supply chain, and options"),
        (name = "Email Digest", description = "Periodic email market sentiment, events, and news summaries delivered at daily or weekly intervals"),
        (name = "Streaming & Kafka", description = "Real-time streaming topic discovery and temporary SASL Kafka consumer credentials management"),
        (name = "Data Retention & Compliance", description = "Regulatory data retention policy management, category lifecycles, and automated data purging"),
        (name = "Risk & Factor Analytics", description = "Quantitative multi-factor regression, risk exposures, betas, t-stats, and model goodness-of-fit metrics"),
        (name = "ESG & Sustainability Analytics", description = "Quantitative Environmental, Social, and Governance (ESG) sentiment scores, keyword mentions, and composite ratings"),
        (name = "Notifications & Alerts", description = "Telegram and Discord real-time alert bot subscriptions and automated event notifications"),
        (name = "Portfolio & Risk Analytics", description = "Mean-Variance (Max Sharpe) and Risk Parity quantitative portfolio asset allocation solvers"),
        (name = "Multilingual & NLP Services", description = "Real-time language identification and multilingual sentiment model routing"),
        (name = "Alpha Signal Validation", description = "Point-in-time sentiment-driven alpha strategy backtesting, performance attribution, and benchmark comparison"),
        (name = "Point-in-Time & Compliance", description = "Historical data state reconstruction, look-ahead-bias validation, and temporal audit trail for regulatory-grade backtesting transparency"),
        (name = "Quantitative Research", description = "Signal quality reporting, Spearman Rank IC, forward return predictive power, horizon decay curves, and systematic bias analysis"),
        (name = "Operational Transparency", description = "Real-time health, uptime, latency, and SLA monitoring of upstream financial data providers (SEC EDGAR, Finnhub, Polygon.io)")
    ),
    info(
        title = "FinText-Alpha-Vectorizer API",
        version = "2.0.0-institutional",
        description = "Ultra-Low-Latency Financial Sentiment Vectorizer & Quantitative Alpha Engine Gateway.\n\n### Authentication\nProtected REST routes require a valid HMAC-SHA256 JWT passed via the `Authorization: Bearer <token>` header. For WebSocket streaming (`/ws`), supply the token in the query string (`/ws?token=<token>`). Obtain temporary credentials via `POST /auth/token`.\n\n### Rate Limiting & Metering\nAll protected endpoints enforce token bucket rate limits (configured via `X-RateLimit-*` response headers) and non-blocking asynchronous usage metering into PostgreSQL.",
        contact(
            name = "FinText Alpha Engineering Team",
            url = "https://github.com/FinText-Alpha-Vectorizer"
        ),
        license(
            name = "Proprietary Institutional License"
        )
    )
)]
pub struct ApiDoc;

/// OpenAPI modifier that transforms paths to `/v1` prefix and ensures public route specifications.
pub struct PublicV1PrefixAddon;

impl Modify for PublicV1PrefixAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let old_paths = std::mem::take(&mut openapi.paths.paths);
        for (path, item) in old_paths {
            // Transform internal path mappings to /v1 public contract
            let new_path = match path.as_str() {
                "/auth/me" => "/v1/users/me".to_string(),
                "/auth/api-keys" => "/v1/users/api-keys".to_string(),
                "/auth/api-keys/{id}" => "/v1/users/api-keys/{id}".to_string(),
                p if p.starts_with("/v1") => p.to_string(),
                p => format!("/v1{}", p),
            };

            openapi.paths.paths.insert(new_path, item);
        }

        // Also add /v1/sentiment/confidence alias if /v1/sentiment is present
        if let Some(sentiment_item) = openapi.paths.paths.get("/v1/sentiment").cloned() {
            openapi
                .paths
                .paths
                .insert("/v1/sentiment/confidence".to_string(), sentiment_item);
        }
    }
}

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::handlers::health::health_check_handler,
        crate::auth::issue_token_handler,
        crate::users::get_me_handler,
        crate::users::create_api_key_handler,
        crate::users::list_api_keys_handler,
        crate::users::delete_api_key_handler,
        crate::handlers::sentiment_feed::get_sentiment_feed_handler,
        crate::handlers::sentiment_history::get_sentiment_history_handler,
        crate::handlers::batch_sentiment::get_batch_sentiment_handler,
        crate::handlers::sentiment::get_sentiment_handler,
        crate::handlers::sentiment_disagreement::get_sentiment_disagreement_handler,
        crate::handlers::sentiment_entities::get_sentiment_entities_handler,
        crate::handlers::sector_sentiment::get_sector_sentiment_handler,
        crate::handlers::news_articles::list_news_articles_handler,
        crate::handlers::events_8k::get_8k_events_handler,
        crate::handlers::earnings_surprise::get_earnings_surprise_handler,
        crate::handlers::transcripts::create_transcript_handler,
        crate::handlers::transcripts::list_transcripts_handler,
        crate::handlers::transcripts::delete_transcript_handler,
        crate::handlers::pit_certificate::get_pit_certificate_handler,
        crate::handlers::pit_replay::get_pit_replay_handler,
        crate::handlers::model_card::get_model_card_handler,
        crate::handlers::symbol_map::get_symbol_map_handler,
        crate::universes::list_universes_handler,
        crate::handlers::signal_quality::post_signal_quality_report_handler,
        crate::handlers::export::export_csv_handler,
        crate::webhooks::register_webhook_handler,
        crate::webhooks::list_webhooks_handler,
    ),
    components(
        schemas(
            HealthResponse,
            IssueTokenRequest,
            IssueTokenResponse,
            AuthErrorResponse,
            UserProfileResponse,
            CreateApiKeyRequest,
            CreateApiKeyResponse,
            ApiKeyItem,
            ListApiKeysResponse,
            DeleteApiKeyResponse,
            RateLimitErrorResponse,
            SentimentFeedParams,
            SentimentFeedItem,
            SentimentFeedResponse,
            SentimentHistoryParams,
            SentimentHistoryResponse,
            SentimentRecord,
            BatchSentimentParams,
            BatchSentimentResponse,
            SentimentResponse,
            SentimentProbabilities,
            SentimentDisagreementResponse,
            SentimentEntitiesParams,
            EntitySentimentItem,
            EntitySentimentResponse,
            SourceBreakdown,
            SectorSentimentParams,
            SectorSentimentResponse,
            NewsArticleMetadata,
            NewsArticleFull,
            NewsArticlesListResponse,
            EightKFiling,
            EightKResponse,
            EarningsSurpriseItem,
            EarningsSurpriseResponse,
            CreateTranscriptRequest,
            TranscriptListParams,
            TranscriptMetadata,
            TranscriptResponse,
            TranscriptListResponse,
            DeleteTranscriptResponse,
            PITCertificateParams,
            PITCertificatePolicies,
            PITCertificateResponse,
            PITCertificateTests,
            PITTestResult,
            PITDuplicateTestResult,
            PITBackfillTestResult,
            PITReplayResponse,
            PITReplaySummary,
            PITReplayConsistency,
            PITReplaySentimentItem,
            PITReplayNewsItem,
            PITReplayFilingItem,
            PITReplayEventItem,
            ModelCardResponse,
            HardwareRequirements,
            LicensingInfo,
            VersionHistoryItem,
            SecurityIdentifiers,
            SymbolMapParams,
            SymbolMapResponse,
            Universe,
            CreateUniverseRequest,
            UpdateUniverseRequest,
            ListUniversesParams,
            ListUniversesResponse,
            DeleteUniverseResponse,
            SignalQualityReportRequest,
            SignalQualityReportResponse,
            ICSummary,
            DecayCurvePoint,
            MarketCapBias,
            ExportCsvParams,
            CreateWebhookRequest,
            DeleteWebhookResponse,
            ListWebhooksResponse,
            WebhookPayload,
            WebhookResponse,
        )
    ),
    modifiers(&SecurityAddon, &PublicV1PrefixAddon),
    tags(
        (name = "System", description = "Liveness and system health monitoring probes"),
        (name = "Authentication", description = "Token generation and user API key management"),
        (name = "Sentiment Analysis", description = "Point-in-Time and real-time asset sentiment signals"),
        (name = "Financial News & Events", description = "Institutional news articles and SEC 8-K / earnings surprise filings"),
        (name = "Transcripts", description = "Earnings call and corporate transcripts"),
        (name = "Governance & Point-in-Time", description = "Point-in-time replay, verification certificates, and model card"),
        (name = "Symbols & Universes", description = "Security identifier mapping and custom asset universes"),
        (name = "Quantitative Research", description = "Signal quality reports and historical CSV dataset export"),
        (name = "Notifications", description = "Asynchronous webhook subscription endpoints")
    ),
    info(
        title = "FinText-Alpha-Vectorizer Public API",
        version = "1.0.0",
        description = "Core Public API Gateway exposing essential quantitative sentiment, filings, PIT, and alpha signals.\n\n### Authentication\nProtected REST routes require a valid Bearer JWT passed via `Authorization: Bearer <token>` or an API Key.\n\n### Versioning\nAll public endpoints are rooted under the `/v1` prefix.",
        contact(
            name = "FinText Alpha Engineering Team",
            url = "https://github.com/FinText-Alpha-Vectorizer"
        ),
        license(
            name = "Proprietary Institutional License"
        )
    )
)]
pub struct PublicApiDoc;
